### ISSUE TITLE
Receive vs destination timestamp

### ISSUE THREAD

**Issue by aanchal4** [ietf-wg-ntp/draft-ietf-ntp-interleaved-modes#1]
For clear distinction between T_2 and T_4 in Section 2 interleaved client/server mode:
T_2: Receive timestamp from the previous packet.
T_4: Destination timestamp of the previous packet.
"For T_4, receive timestamp of the previous packet" is ambiguous and also not in line with the RFC5905.

**Comment by mlichvar** [comment]
I think the same ambiguity is with the "transmit timestamp of/from". Destination timestamp is a term for local receive timestamps in RFC 5905, but there doesn't seem to be a term for local transmit timestamps. We can't call it origin timestamp, because that would be a destination timestamp in the interleaved mode.

Do you think it would be better if we used terms "local receive timestamp" and "local transmit timestamp"?
